name: menstrual_cycle_widget
description: "The 'Menstrual Cycle Widget' Widget is a comprehensive and customizable widget designed to help users to show their menstrual cycles seamlessly."
version: 2.1.2
repository: https://github.com/sandipkalola/menstrual_cycle_widget
issue_tracker: https://github.com/sandipkalola/menstrual_cycle_widget/issues
funding:
  - https://github.com/sponsors/sandipkalola

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.4.1
  path_provider: ^2.1.5
  path: ^1.9.0
  intl: ^0.18.1
  encrypt: ^5.0.3
  crypto: ^3.0.6
  syncfusion_flutter_charts: ^27.2.3
  syncfusion_flutter_pdf: ^27.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  assets:
    - assets/images/

# This package supports all platforms listed below.
platforms:
  android:
  ios:

topics:
  - menstrualcycle
  - calenderview
  - period
  - health
  - menstruation
